# Uncomment the next line to define a global platform for your project

target 'Advertising' do
platform :ios, '9.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Advertising

  pod 'AFNetworking', '~> 3.0'
  pod 'ReactiveObjC', '~> 3.1.0' 
  pod 'Masonry'
  pod 'SDWebImage', '~> 5.0'
#  pod 'SDWebImage/WebP'
  pod 'MJRefresh'
  pod 'YTKNetwork'
  pod 'IQKeyboardManager'
  pod 'MJExtension'
  pod 'MJRefresh'
  pod 'MBProgressHUD'
#  pod 'MLeaksFinder'
  #pod 'Bugly', '~> 2.5.0'
  pod 'PPBadgeView'
  pod 'SDCycleScrollView'
  pod 'TYPagerController'
  pod 'AZTools'
  pod 'AlipaySDK-iOS'
  pod 'WechatOpenSDK'
  pod 'ZFPlayer/ControlView', '~> 3.0'
  pod 'ZFPlayer/AVPlayer', '~> 3.0'
  pod 'TZImagePickerController'
  pod 'SZTextView'

end
